
#define IDDIALOG_PROPERTIES   1

#define IDITEM_HTML_HEADER    101
#define IDITEM_HTML_PAGE      102
#define IDITEM_HTML_FOOTER    103

#define IDTIMER_GOTO_PAGE     100
#define TIMER_GOTO_PAGE_DURATION  500

#define WM_PRINT_DOCUMENT     (WM_USER + 1)




